### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by r00bal** [AdamczukPawel/goit-react-hw-06-phonebook#1]
https://github.com/AdamczukPawel/goit-react-hw-06-phonebook/blob/48fec13d9726865e407a4b692a920308a63886e7/src/components/App.jsx#L10-L15

Nie wystarczy store subscribe ze store.js :
```
store.subscribe(() => saveToLocalStorage(store.getState()));
```

**Comment by AdamczukPawel** [comment]
Zostało po wcześniejszym pomyśle na użycie localStorage :)
